apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    io.kompose.service: web
spec:
  type: NodePort
  ports:
    - port: 30001
      nodePort: 30001
      targetPort: 8888
      name: http
  selector:
    io.kompose.service: web
