---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: waf-new-alert-rule-info
spec:
  summary: "WAF new waf-alert-942100"
  description: "Test WAF Global Alert"
  severity: 1
  dataSet: waf
  period: 1m
  lookback: 1m
  query: '"rule_info" IN {"*1005*"}'
  threshold: 0
  condition: gt

---

apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: waf.modsecurity-ruleset-match
spec:

  description: Generate alerts for all mod security ruleset matches
  summary: "[WAF] Malicious HTTP request to ${destination.hostname} detected from ${source.ip}"
  severity: 100
  dataSet: waf
  period: 1m
  lookback: 1m
  query: msg="WAF check FAILED!"
  aggregateBy: [rule_info, method, path, destination.hostname, destination.ip, source.hostname, source.ip]
